services:
  - type: web
    name: ollama-service
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 11434
    scaling:
      minInstances: 1
      maxInstances: 1
