services:
  - type: web
    name: ollama
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: PORT
        value: 11434
